# Language support to enable
language: python

# Specifying Python versions
python:
  - "2.7"

# Services to set up and start
services:
  - docker

# Scripts to run before the script stage
before_script: pip install docker-compose

# Scripts to run at the script stage
script:
  - docker-compose run app sh -c "python manage.py test && flake8"
